# The URL the site will be built for
base_url = "https://marginalwords.github.io"

title = "marginal words"
theme = "Seje2"
output_dir = "public"
# Whether to automatically compile all Sass files in the sass directory
compile_sass = true
# What language to use
default_language = "en"
generate_feed = true


# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = false

[extra]
# show Chinese date format instead of normal date format
seje_chinese_date = false
# show summary instead of the whole article on the index page
seje_show_summary_only = false
# Google Font API mirror URLs (for China mainland users, try fonts.loli.net)
seje_font_mirror = "fonts.googleapis.com"
# whether use traditional Chinese style vertical layout
seje_vertical_layout = false
# additional custom fonts to include (must be in CSS font-family format)
seje_custom_fonts = ""
# whether enable darkmode. Possible values: auto, always, never
seje_darkmode = "auto"
# Your site blog links
seje_menu_links = [
    {url = "$BASE_URL/", name = "home"},
    {url = "$BASE_URL/archives", name = "archives"},
    {url = "$BASE_URL/about",  name = "about"},
    {url = "$BASE_URL/atom.xml", name = "rss"},
]

[languages.en.translations]
title = "marginal Words"
home = "Home"
archives = "Archives"
about = "About"
rss = "RSS"
more = "More"
olderArticle = "Load More"
newer = "Next"
older = "Previous"
loading = "Loading…"

